// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chprummpkojvcawbycus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNocHJ1bW1wa29qdmNhd2J5Y3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjYxMzQsImV4cCI6MjA2NzU0MjEzNH0.ITjQ-OADSzCbBR-GT525SHo_fRHchd4kI2mqtqnJK70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});